name: Balamaika Studio
theme: minima
description: Currency Converter - Qrate
Thank you for downloading our app!

In case you have any problems or have suggestions, please reach out at balamaika.studio@gmail.com

Thank you!
Balamaika Team

